import Head from 'next/head'
import Header from '../components/Header'
import Image from 'next/image'
import Footer from '../components/Footer'
import { MagnifyingGlassIcon, MicrophoneIcon } from '@heroicons/react/24/solid'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header  */}
      <Header/>

      {/* body  */}
      <form className='flex flex-col items-center mt-40 '>
        <Image 
        src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/1200px-Google_2015_logo.svg.png" width="300" objectFit='cover' height="100"/>

        <div className='flex w-3/6 mt-5 mx-50  border border-gray-200 rounded-full'>
          <MagnifyingGlassIcon className="h-5 text-gray-500 right-3 left-16   "/>
          <input type="text" className="flex-grow focus:outline-none hover:shadow-lg  focus-within:shadow-lg px-5 py-3 rounded-full items-center sm:max-w-xl lg:max-w-2xl" />
          <MicrophoneIcon className='h-5  -translate-x-16 translate-y-1/3' />
        </div>
        
        
        <div className='my-5 flex flex-row sm:flex-row space-y-2 mt-8 sm:space-y-0 sm:space-x-4 justify-center'>
          <button className='btn mr-8 '> Google Search</button>
          <button className='btn'> I'm Feeling Lucky</button>
        </div>



      </form>


      {/* footer  */}
      
      <Footer/>

    </div>
  )
}
